### ISSUE TITLE
Tracklist enhancements

### ISSUE THREAD

**Issue by noraheuer** [audiotheme/audiotheme#51]
I would like to see a separation of Track # and Play/Pause button in a track list.
1. Track # should always be visible.
2. Play/Pause button should only be shown when Javascript is available.
3. Play button should always be shown when there is a playable file and JS available (not only onHover) as a separate button --- that could improve accessibility and keyboard navigation.
4. If track has a duration set, it should always be shown ----- it is currently always -:-- or hidden entirely when there is no playable file.

**Comment by bradyvercher** [comment]
Hi @noraheuer! Thanks so much for the suggestions. We would love to make quite a few improvements to track lists, but have been hesitant to make changes due to backward compatibility concerns for users who aren't using one of our themes.

We're planning to release a fork of this plugin in the WordPress.org repository at some point in the future, so we'll definitely improve the behavior then.

In the meantime, I think 2 in your list is already taken care of since the play button won't show if JavaScript is disabled. We handle 4 in our themes, but I think we can switch the plugin templates to show the duration instead of the current time by default.

**Comment by noraheuer** [comment]
Thanks @bradyvercher,
yes, I assumed as much re. backward compatibility for #1 and #3.
After further investigation, sorry #2 and #4 are issues with the Hammer theme not AudioTheme directly, so please ignore:
- Hammer sets .is-playable in function hammer_track_attributes (hammer/includes/plugins/audiotheme.php)
- Hammer sets .track-duration to 'display:none' (in audiotheme.css) unless .is-playable is set on a parent

**Comment by bradyvercher** [comment]
Hmm, I'll open an issue for Hammer so we can at least make sure the duration always shows.
